### ISSUE TITLE
Review `yield()` in the swivel lend method

### ISSUE THREAD

**Issue by JTraversa** [Swivel-Finance/gost#273]
When we lend with Swivel, we receive underlying and PTs.

The current implementation takes the underlying returned and purchases yield protocol PTs with it to increase yield marginally.

We should review the efficiency of this methodology, and alternatives.

### Alternative 1: Leave underlying dormant until maturity 
Pros:
- Could mint them 1:1 amounts of PTs with it
- Least gas cost

Cons: 
- Leaves potential interest on the table
--------------------
### Alternative 2: Deposit to comp and keep interest for ourselves as additional fee
Pros:
- Could mint them 1:1 amounts of PTs with it
- More $ for us

Cons:
- Doesnt optimize for user
--------------------
### Alternative 3: As is, lend out the remaining at a fixed rate
Pros:
- Utilizes all capital
- Optimizes for user yield

Cons:
- Gas costs may eclipse additional yield gain

**Comment by robrobbins** [comment]
also good stuff...

**Comment by sourabhmarathe** [comment]
I think there is an additional alternative here where we allow the user to decide. So we can pass a boolean to the method that states if the user would like to optimize. Then we can let the fee market do the work of determining whether or not it is worth it to put that leftover capital to work. 

The way this would work is the user could opt for the lower gas option if it makes sense for them. In that case, the tokens would lie dormant for the duration of the loan. Otherwise, the user can elect to put the money to work, and we would go ahead and lend out the remaining money. 

I do not think we should do alternative 2 unless it is very clear to the user that the extra money is going towards a fee. Since it complicates the fee picture, this may lead to a worse UX (i.e. fee is a base rate + this extra $ they make off me??).

**Comment by JTraversa** [comment]
^^ I like Sourabh's option.

Not just to allow the market to decide, but we could identify the break even gas price and automatically apply the boolean to effectively optimize the yield.

If gas is too high, `false` and retain yield in underlying.

If gas is low enough, `true` and purchase from yield?

**Comment by futurethang** [comment]
This does sound good. I agree that unclear fees ultimately smells bad and reflect poorly on the protocol. Adding mechanisms to squeeze the extra bits of juice into the user's cup is good all-around, however implemented.

**Comment by sourabhmarathe** [comment]
Looks like we have consensus on making `yield()` flexible. 

**Should we calculate the gas cost in the smart contract or leave it to the front end/user to pass a boolean to the `lend` call?**

We can get the current gas rate by calling `tx.gas` and then checking against some minimum gas cost, but that leaves us at risk of having to monitor that minimum value (which can also change rapidly under different market conditions). The benefit of this is that it keeps the interface to our contract simple and makes for a simpler UX.

The other choice is we have the front end/user determine which route they'd like to take by passing a boolean to lend functions that call `yield()`. The benefit of this is that we don't have to worry about the gas market going against the user all of a sudden.

**Comment by sourabhmarathe** [comment]
See the PR #305 for a potential implementation of this. 

After discussing with @JTraversa and @robrobbins, we decided to support `YieldSpace` via an external router. We will open up another ticket to do that.
